name: Demo-cache

on:
  workflow_dispatch:

jobs:
  job-1:
    runs-on: ubuntu-latest

    steps:
      - name: Restore cache
        id: demo-cache
        uses: actions/cache@v4
        with:
          path: myDir
          key: my-demo-code

      - name: Generate content if cache miss
        if: steps.demo-cache.outputs.cache-hit != 'true'
        run: |
          echo "Cache is missing, generating content"
          mkdir -p myDir
          date > myDir/myFile.txt

      - name: Verify cache
        run: |
          echo "Cache hit? -> ${{ steps.demo-cache.outputs.cache-hit }}"
          ls -la myDir
          cat myDir/myFile.txt