name: filter-files-on-push

on:
  push:
    branches:
      - main
    paths:
        - trigger-file.cpp
jobs:
  trigger-on-push:
    runs-on: ubuntu-latest
    steps:
      - run: echo "triggered by a trigger push file named trigger-file"
