name: Pass values between jobs

on:
  workflow_dispatch:

jobs:
  producer:
    runs-on: ubuntu-latest

    outputs:
      foo: ${{ steps.generate-foo.outputs.foo }}

    steps:
      - name: Generate and export/pass foo
        id: generate-foo
        run: |
          foo=bar

          echo "foo=${foo}" >> "$GITHUB_OUTPUT"
          echo "FOO=${foo}" >> "$GITHUB_ENV"

      - name: Check value inside producer job
        run: |
          echo "FOO from GITHUB_ENV: $FOO"
          echo "foo from step output: ${{ steps.generate-foo.outputs.foo }}"

  consumer:
    runs-on: ubuntu-latest
    needs: [producer]

    steps:
      - name: Check value inside consumer job
        run: |
          echo "Value from producer: ${{ needs.producer.outputs.foo }}"
          echo "FOO in consumer: ${FOO:-<UNSET>}"